[package]
name = "packets"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0"
packets-macro = { path = "packets_macro" } # from a path in the local filesystem
tokio = { version = "1.5.0", features = ["full"] }
